version: "3.7"

services:
  app:
    build:
      args:
        user: boilerplate-user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: boilerplate
    container_name: boilerplate-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - boilerplate

  mysql:
    image: 'mysql/mysql-server:8.0'
    container_name: boilerplate-db
    restart: unless-stopped
    ports:
        - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ROOT_HOST: "%"
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - boilerplate

  nginx:
    image: nginx:1.17-alpine
    container_name: boilerplate-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - boilerplate

networks:
  boilerplate:
    driver: bridge
